#############################################################################
# Makefile for building: LiZi-qt
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  BERN-qt.pro
# Template: app
# Command: c:\Qt\qt_static\bin\qmake.exe "USE_IPV6=0" "USE_UPNP=0" -o Makefile BERN-qt.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = c:\Qt\qt_static\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: BERN-qt.pro ../../../../Qt/qt_static/mkspecs/win32-g++/qmake.conf ../../../../Qt/qt_static/mkspecs/features/spec_pre.prf \
		../../../../Qt/qt_static/mkspecs/qdevice.pri \
		../../../../Qt/qt_static/mkspecs/features/device_config.prf \
		../../../../Qt/qt_static/mkspecs/qconfig.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qico.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qwindows.pri \
		../../../../Qt/qt_static/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../../../Qt/qt_static/mkspecs/features/qt_functions.prf \
		../../../../Qt/qt_static/mkspecs/features/qt_config.prf \
		../../../../Qt/qt_static/mkspecs/features/win32/qt_config.prf \
		../../../../Qt/qt_static/mkspecs/win32-g++/qmake.conf \
		../../../../Qt/qt_static/mkspecs/features/spec_post.prf \
		../../../../Qt/qt_static/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/qt_static/mkspecs/features/default_pre.prf \
		../../../../Qt/qt_static/mkspecs/features/win32/default_pre.prf \
		../../../../Qt/qt_static/mkspecs/features/resolve_config.prf \
		../../../../Qt/qt_static/mkspecs/features/exclusive_builds_post.prf \
		../../../../Qt/qt_static/mkspecs/features/default_post.prf \
		../../../../Qt/qt_static/mkspecs/features/win32/rtti.prf \
		../../../../Qt/qt_static/mkspecs/features/precompile_header.prf \
		../../../../Qt/qt_static/mkspecs/features/warn_on.prf \
		../../../../Qt/qt_static/mkspecs/features/qt.prf \
		../../../../Qt/qt_static/mkspecs/features/resources.prf \
		../../../../Qt/qt_static/mkspecs/features/moc.prf \
		../../../../Qt/qt_static/mkspecs/features/win32/opengl.prf \
		../../../../Qt/qt_static/mkspecs/features/uic.prf \
		../../../../Qt/qt_static/mkspecs/features/win32/windows.prf \
		../../../../Qt/qt_static/mkspecs/features/testcase_targets.prf \
		../../../../Qt/qt_static/mkspecs/features/exceptions.prf \
		../../../../Qt/qt_static/mkspecs/features/yacc.prf \
		../../../../Qt/qt_static/mkspecs/features/lex.prf \
		BERN-qt.pro \
		C:/Qt/qt_static/lib/qtmaind.prl \
		C:/Qt/qt_static/lib/Qt5PrintSupport.prl \
		C:/Qt/qt_static/lib/Qt5Widgets.prl \
		C:/Qt/qt_static/lib/Qt5Gui.prl \
		C:/Qt/qt_static/lib/Qt5Network.prl \
		C:/Qt/qt_static/lib/Qt5Core.prl \
		C:/Qt/qt_static/plugins/printsupport/windowsprintersupport.prl \
		C:/Qt/qt_static/plugins/platforms/qwindows.prl \
		C:/Qt/qt_static/plugins/imageformats/qico.prl \
		C:/Qt/qt_static/plugins/bearer/qgenericbearer.prl \
		C:/Qt/qt_static/plugins/bearer/qnativewifibearer.prl
	$(QMAKE) "USE_IPV6=0" "USE_UPNP=0" -o Makefile BERN-qt.pro
../../../../Qt/qt_static/mkspecs/features/spec_pre.prf:
../../../../Qt/qt_static/mkspecs/qdevice.pri:
../../../../Qt/qt_static/mkspecs/features/device_config.prf:
../../../../Qt/qt_static/mkspecs/qconfig.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qico.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qminimal.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qnativewifibearer.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qsvg.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_plugin_qwindows.pri:
../../../../Qt/qt_static/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../../../../Qt/qt_static/mkspecs/features/qt_functions.prf:
../../../../Qt/qt_static/mkspecs/features/qt_config.prf:
../../../../Qt/qt_static/mkspecs/features/win32/qt_config.prf:
../../../../Qt/qt_static/mkspecs/win32-g++/qmake.conf:
../../../../Qt/qt_static/mkspecs/features/spec_post.prf:
../../../../Qt/qt_static/mkspecs/features/exclusive_builds.prf:
../../../../Qt/qt_static/mkspecs/features/default_pre.prf:
../../../../Qt/qt_static/mkspecs/features/win32/default_pre.prf:
../../../../Qt/qt_static/mkspecs/features/resolve_config.prf:
../../../../Qt/qt_static/mkspecs/features/exclusive_builds_post.prf:
../../../../Qt/qt_static/mkspecs/features/default_post.prf:
../../../../Qt/qt_static/mkspecs/features/win32/rtti.prf:
../../../../Qt/qt_static/mkspecs/features/precompile_header.prf:
../../../../Qt/qt_static/mkspecs/features/warn_on.prf:
../../../../Qt/qt_static/mkspecs/features/qt.prf:
../../../../Qt/qt_static/mkspecs/features/resources.prf:
../../../../Qt/qt_static/mkspecs/features/moc.prf:
../../../../Qt/qt_static/mkspecs/features/win32/opengl.prf:
../../../../Qt/qt_static/mkspecs/features/uic.prf:
../../../../Qt/qt_static/mkspecs/features/win32/windows.prf:
../../../../Qt/qt_static/mkspecs/features/testcase_targets.prf:
../../../../Qt/qt_static/mkspecs/features/exceptions.prf:
../../../../Qt/qt_static/mkspecs/features/yacc.prf:
../../../../Qt/qt_static/mkspecs/features/lex.prf:
BERN-qt.pro:
C:/Qt/qt_static/lib/qtmaind.prl:
C:/Qt/qt_static/lib/Qt5PrintSupport.prl:
C:/Qt/qt_static/lib/Qt5Widgets.prl:
C:/Qt/qt_static/lib/Qt5Gui.prl:
C:/Qt/qt_static/lib/Qt5Network.prl:
C:/Qt/qt_static/lib/Qt5Core.prl:
C:/Qt/qt_static/plugins/printsupport/windowsprintersupport.prl:
C:/Qt/qt_static/plugins/platforms/qwindows.prl:
C:/Qt/qt_static/plugins/imageformats/qico.prl:
C:/Qt/qt_static/plugins/bearer/qgenericbearer.prl:
C:/Qt/qt_static/plugins/bearer/qnativewifibearer.prl:
qmake: FORCE
	@$(QMAKE) "USE_IPV6=0" "USE_UPNP=0" -o Makefile BERN-qt.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\Users\admin\Documents\BERNcash-master\lizi-qt_plugin_import.cpp

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
